### ISSUE TITLE
misskeyでメンションに反応しない時がある

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#2763]
hato と手動で入力した時は反応するが、 自動補完でhatoにメンションした時は反応しない感じ？

**Comment by nakkaa** [comment]
```
hato-bot-hato-bot-1  | Traceback (most recent call last):
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 21, in <module>
hato-bot-hato-bot-1  |     main()
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 17, in main
hato-bot-hato-bot-1  |     run.main()
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 240, in main
hato-bot-hato-bot-1  |     asyncio.get_event_loop().run_until_complete(misskey_runner())
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
hato-bot-hato-bot-1  |     return future.result()
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 225, in misskey_runner
hato-bot-hato-bot-1  |     and misskey_client.i()["id"] in mentions
hato-bot-hato-bot-1  |         ^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/misskey/misskey.py", line 220, in i
hato-bot-hato-bot-1  |     return self.__request_api('i')
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/misskey/misskey.py", line 149, in __request_api
hato-bot-hato-bot-1  |     response = self.__session.post(
hato-bot-hato-bot-1  |                ^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
hato-bot-hato-bot-1  |     return self.request("POST", url, data=data, json=json, **kwargs)
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
hato-bot-hato-bot-1  |     resp = self.send(prep, **send_kwargs)
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
hato-bot-hato-bot-1  |     r = adapter.send(request, **kwargs)
hato-bot-hato-bot-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 578, in send
hato-bot-hato-bot-1  |     raise ReadTimeout(e, request=request)
hato-bot-hato-bot-1  | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='misskey.7ka.org', port=443): Read timed out. (read timeout=15.0)
```

**Comment by nakkaa** [comment]
read timeout=15.0 を伸ばすかretryする機構を設ければ解消する？
