### ISSUE TITLE
misskeyと切断されるとエラーが出て復帰しない

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#2764]

**Comment by nakkaa** [comment]
```
hato-bot-hato-bot-1  | Execute: CREATE TABLE IF NOT EXISTS vocabulary
hato-bot-hato-bot-1  | (
hato-bot-hato-bot-1  |     no SERIAL UNIQUE,
hato-bot-hato-bot-1  |     word TEXT
hato-bot-hato-bot-1  | Traceback (most recent call last):
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 21, in <module>
hato-bot-hato-bot-1  | );
hato-bot-hato-bot-1  | 
hato-bot-hato-bot-1  | Execute: CREATE TABLE IF NOT EXISTS slack_client_msg_id
hato-bot-hato-bot-1  | (
hato-bot-hato-bot-1  |     client_msg_id TEXT UNIQUE,
hato-bot-hato-bot-1  |     created_at TIMESTAMP
hato-bot-hato-bot-1  | );
hato-bot-hato-bot-1  | 
hato-bot-hato-bot-1  |     main()
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 17, in main
hato-bot-hato-bot-1  |     run.main()
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 240, in main
hato-bot-hato-bot-1  |     asyncio.get_event_loop().run_until_complete(misskey_runner())
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
hato-bot-hato-bot-1  |     return future.result()
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 198, in misskey_runner
hato-bot-hato-bot-1  |     async with websockets.connect(
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 637, in __aenter__
hato-bot-hato-bot-1  |     return await self
hato-bot-hato-bot-1  |            ^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
hato-bot-hato-bot-1  |     return await self.__await_impl__()
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
hato-bot-hato-bot-1  |     await protocol.handshake(
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 329, in handshake
hato-bot-hato-bot-1  |     raise InvalidStatusCode(status_code, response_headers)
hato-bot-hato-bot-1  | websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
```
