### ISSUE TITLE
docker-compose up(初回)すると tionalError: server does not support SSL, but SSL was required が発生する

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#281]
docker-compose build --no-cache してから docker-compose up すると以下のエラーが発生する。(初回のみ)

```
2gimac-180418$ ~/Documents/develop/hato-bot/setup docker-compose up   
Starting setup_postgres_1 ... done
Recreating setup_hato-bot_1 ... done
Attaching to setup_postgres_1, setup_hato-bot_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2020-08-20 11:30:16.884 UTC [1] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
postgres_1  | 2020-08-20 11:30:16.884 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-08-20 11:30:16.885 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-08-20 11:30:16.888 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-08-20 11:30:16.938 UTC [21] LOG:  database system was shut down at 2020-08-20 11:22:17 UTC
postgres_1  | 2020-08-20 11:30:16.953 UTC [1] LOG:  database system is ready to accept connections
hato-bot_1  | Loading .env environment variables…
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Can not connect to database.
hato-bot_1  | Traceback (most recent call last):
hato-bot_1  |   File "entrypoint.py", line 21, in <module>
hato-bot_1  |     main()
hato-bot_1  |   File "entrypoint.py", line 15, in main
hato-bot_1  |     wait_db.main()
hato-bot_1  |   File "/usr/src/app/wait_db.py", line 33, in main
hato-bot_1  |     wait_db()
hato-bot_1  |   File "/usr/src/app/wait_db.py", line 23, in wait_db
hato-bot_1  |     raise _e
hato-bot_1  |   File "/usr/src/app/wait_db.py", line 18, in wait_db
hato-bot_1  |     with Database() as _db:
hato-bot_1  |   File "/usr/src/app/library/database.py", line 18, in __init__
hato-bot_1  |     raise _e
hato-bot_1  |   File "/usr/src/app/library/database.py", line 15, in __init__
hato-bot_1  |     self.conn = psycopg2.connect(conf.DB_URL, sslmode='require')
hato-bot_1  |   File "/usr/src/venv/app-lp47FrbD/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
hato-bot_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
hato-bot_1  | psycopg2.OperationalError: server does not support SSL, but SSL was required
hato-bot_1  | 
```

**Comment by massongit** [comment]
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
```

`setup/pgsql-data`を消した上でやると初期化スクリプトが走ってうまくいきそう

**Comment by nakkaa** [comment]
ダメでした。
alpainにopensslを入れる必要がありそうです。
