### ISSUE TITLE
Misskey v2023.12.2で動かない

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#3529]
```
hato-bot-hato-bot-1  | Traceback (most recent call last):
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 21, in <module>
hato-bot-hato-bot-1  |     main()
hato-bot-hato-bot-1  |   File "/usr/src/app/entrypoint.py", line 17, in main
hato-bot-hato-bot-1  |     run.main()
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 251, in main
hato-bot-hato-bot-1  |     asyncio.get_event_loop().run_until_complete(misskey_runner())
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
hato-bot-hato-bot-1  |     return future.result()
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/src/app/run.py", line 200, in misskey_runner
hato-bot-hato-bot-1  |     async with websockets.connect(
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 629, in __aenter__
hato-bot-hato-bot-1  |     return await self
hato-bot-hato-bot-1  |            ^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
hato-bot-hato-bot-1  |     return await self.__await_impl__()
hato-bot-hato-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
hato-bot-hato-bot-1  |     await protocol.handshake(
hato-bot-hato-bot-1  |   File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 325, in handshake
hato-bot-hato-bot-1  |     raise InvalidStatusCode(status_code, response_headers)
hato-bot-hato-bot-1  | websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
hato-bot-hato-bot-1 exited with code 1
```

**Comment by nakkaa** [comment]
> Fix: サードパーティアプリケーションがWebsocket APIに無条件にアクセスできる問題を修正

これのせいか？
Fix: サードパーティアプリケーションがWebsocket APIに無条件にアクセスできる問題を修正

**Comment by nakkaa** [comment]
APIキーを発行する際に アカウントの情報を見る も追加する必要がある。
https://github.com/misskey-dev/misskey/compare/2023.12.0...2023.12.1#diff-ba60aef03407c0a4fd71ad35a8d5c2c66c30497fb462fc41bf7ec7f2c32aa3e3R75
