### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2'

### ISSUE THREAD

**Issue by bgpat** [dev-hato/hato-bot#366]
https://github.com/dev-hato/hato-bot/commit/2250d47658a7a8e74ffd10bf5da25ca3cafd3243 を heroku にデプロイすると死ぬ

```
2020-09-18T16:42:40.563700+00:00 app[web.1]: Traceback (most recent call last):
2020-09-18T16:42:40.563721+00:00 app[web.1]:   File "entrypoint.py", line 7, in <module>
2020-09-18T16:42:40.563722+00:00 app[web.1]:     import create_env
2020-09-18T16:42:40.563722+00:00 app[web.1]:   File "/usr/src/app/create_env.py", line 5, in <module>
2020-09-18T16:42:40.563723+00:00 app[web.1]:     from library.database import Database
2020-09-18T16:42:40.563723+00:00 app[web.1]:   File "/usr/src/app/library/database.py", line 5, in <module>
2020-09-18T16:42:40.563723+00:00 app[web.1]:     import psycopg2
2020-09-18T16:42:40.563724+00:00 app[web.1]: ModuleNotFoundError: No module named 'psycopg2'
2020-09-18T16:42:40.628413+00:00 heroku[web.1]: Process exited with status 1
2020-09-18T16:42:40.665826+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by bgpat** [comment]
docker image に Pipfile を入れたら動いた

```diff
$ git diff origin/develop 
diff --git a/Dockerfile b/Dockerfile
index e7aab94..9773623 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -4,6 +4,7 @@ ENV WORKON_HOME=/usr/src/venv
 
 WORKDIR /usr/src/app
 
+COPY Pipfile Pipfile
 COPY Pipfile.lock-3.8 Pipfile.lock
 
 # 実行時に必要なパッケージ (グループ名: .used-packages)
```

![image](https://user-images.githubusercontent.com/6045753/93627575-1b2c3180-fa20-11ea-8f47-5433fd3f2986.png)
